package com.podcast.podcast.enums;

public enum ErrorCode {

    VALIDATION_ERROR,
    DATA_INTEGRITY_VIOLATION,
    RATE_LIMIT_EXCEEDED,
    TIMEOUT_ERROR,
    RESOURCE_NOT_FOUND,
    UNSUPPORTED_MEDIA_TYPE,
    BUSINESS_RULE_VIOLATION,
    ATTACHMENT_UPLOAD_ERROR,
    PAYLOAD_TOO_LARGE
}
